"""Edited the relationships

Revision ID: 0ce66b705996
Revises: 9c31e9c8dd18
Create Date: 2023-09-07 10:24:57.711568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce66b705996'
down_revision = '9c31e9c8dd18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###